### ISSUE TITLE
Initializer fails with ArgumentError: Missing `secret_key_base` for 'test_data' environment, set this string with `bin/rails credentials:edit`

### ISSUE THREAD

**Issue by mdoel** [testdouble/test_data#2]
It seems that the `test_data:install` task wants to initialize the new `test_data` environment. If you are in a repo that has a `config/credentials.yml.enc` but you are unable to edit that with `rails credentials:edit` (i.e. because you don't have a `config/master.key` or haven't set `RAILS_MASTER_KEY`, the environment creation throws an exception.

**Comment by searls** [comment]
Thanks for the report @mdoel -- sorry for taking my time in looking into this. Looks like it's still an issue as of 49768a2.

To reproduce:

```
$ bin/rails credentials:edit
# save the file
$ mv config/master.key someplace/else
$ bin/rake test_data:install
$ RAILS_ENV=test_data bin/rails server
```

Will yield this error on each request: 

```
2021-07-06 09:03:45 -0400 Rack app ("GET /" - (127.0.0.1)): #<ArgumentError: Missing `secret_key_base` for 'test_data' environment, set this string with `bin/rails credentials:edit`>
```

This doesn't happen to `development`, indicating that it's treated differently for some reason.

**Comment by searls** [comment]
Yeah, [sure enough](https://github.com/rails/rails/blob/main/railties/lib/rails/application.rb#L433-L441):

```ruby
    def secret_key_base
      if Rails.env.development? || Rails.env.test?
        secrets.secret_key_base ||= generate_development_secret
      else
        validate_secret_key_base(
          ENV["SECRET_KEY_BASE"] || credentials.secret_key_base || secrets.secret_key_base
        )
      end
    end
```

**Comment by searls** [comment]
If we were to slam this lovely private-method call into `config/environments/test_data.rb`, it would work:

```ruby
Rails.application.secrets.secret_key_base ||= Rails.application.send(:generate_development_secret)
```

The number of places in which Rails hardcodes `Rails.env.development? || Rails.env.test?` or similar is frustrating, given its support for arbitrarily-many environments (the undocumented working assumption appears to be that all non-development/test environments are production-like)
